export const languages = {
	german: {
		MANAGE_CAMPAIGN: 'Kampagnen verwalten',
		UC_CAMP: 'Kommende Kampagnen',
		LIVE_CAMP: 'Live-Kampagnen',
		PAST_CAMP: 'Vergangene Kampagnen',
		VIEW_PRICE: 'Preise anzeigen',
		SCH_AGAIN: 'Planen Sie erneut',
		END_ON: 'endet am',
		DAY_AGO: 'Vor Tagen',
		DAY_AHEAD: 'Tage voraus',
		ONE_WEEK_ONE_MONTH: '1 Woche - 1 Monat',
		SIX_MONTH: '6 Monate',
		ONE_YEAR: '1 Jahr',
		Close: 'Schließen',
		DATE: 'DATUM',
		CAMPAIGN: 'KAMPAGNE',
		VIEW: 'AUSSICHT',
		ACTIONS: 'AKTIONEN',
		PRICING: 'Preisgestaltung',
		CSV: 'CSV',
		REPORT: 'Bericht',
		Jan: 'Januar',
		Feb: 'Februar',
		March: 'März',
		April: 'April',
		May: 'Kann',
		Jun: 'Juni',
		Jul: 'Juli',
		Aug: 'Aug',
		Sep: 'Sep',
		Oct: 'Oktober',
		Nov: 'Nov',
		Dec: 'Dezember',
		LANG_ENG: 'English',
		LANG_GER: 'Deutsche',
		SELECT_LANG: 'Sprache auswählen'
	},
	english: {
		MANAGE_CAMPAIGN: 'Manage Campaigns',
		UC_CAMP: 'Upcoming Campaigns',
		LIVE_CAMP: 'Live Campaigns',
		PAST_CAMP: 'Past Campaigns',
		VIEW_PRICE: 'View Pricing',
		SCH_AGAIN: 'Schedule Again',
		END_ON: 'ends on',
		DAY_AGO: 'days ago',
		DAY_AHEAD: 'days ahead',
		ONE_WEEK_ONE_MONTH: '1 Week - 1 Month',
		SIX_MONTH: '6 Months',
		ONE_YEAR: '1 Year',
		Close: 'Close',
		DATE: 'DATE',
		CAMPAIGN: 'CAMPAIGN',
		VIEW: 'VIEW',
		ACTIONS: 'ACTIONS',
		PRICING: 'Pricing',
		Jan: 'Jan',
		Feb: 'Feb',
		March: 'March',
		April: 'April',
		May: 'May',
		Jun: 'Jun',
		Jul: 'Jul',
		Aug: 'Aug',
		Sep: 'Sep',
		Oct: 'Oct',
		Nov: 'Nov',
		Dec: 'Dec',
		CSV: 'CSV',
		REPORT: 'Report',
		LANG_ENG: 'English',
		LANG_GER: 'German',
		SELECT_LANG: 'Select Language'
	},
};
